### ISSUE TITLE
Opacity Selections

### ISSUE THREAD

**Issue by jmeilander** [qiime2/q2-emperor#105]
It would be wonderful to have the option to select multiple categories when adjusting the opacity and adjust them all at once rather than currently choosing and adjusting each one individually. I.e. I have 17 choices and I want 16 of them to be set at 0.1. Selecting each of those at once and adjusting the opacity to 0.1 would speed things up. 

Love, 
Teammate Jeff

**Comment by mortonjt** [comment]
So this particular usecase can already be done in Emperor.  Set the global opacity to 0.1, and set the item you are interested to 1.

**Comment by jmeilander** [comment]
Thanks!
