### ISSUE TITLE
sample shape causes color to change

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-emperor#17]
I am really enjoying this new feature.

But non-sphere shapes cause the color to lighten. e.g., in the attached plot there should be 5 colors (I pasted the color key below).

Also, just a general comment — non-sphere shapes don't look great in 3D, as only the spheres have good depth. Shape selection + [2D plots](https://github.com/biocore/emperor/issues/303) = better choices.

![image](https://cloud.githubusercontent.com/assets/1907564/19494533/3ea4d386-9545-11e6-8943-beeeae11ff97.png)
![image](https://cloud.githubusercontent.com/assets/1907564/19494588/6e74d462-9545-11e6-8be8-e6a10d8f393f.png)

**Comment by jairideout** [comment]
@ElDeveloper is this a general Emperor issue? If so, probably makes sense to move there since the plugin is just wrapping Emperor.

**Comment by ElDeveloper** [comment]
Yes, this would be an issue (an important one) for emperor.

**Comment by jairideout** [comment]
Sounds good, @nbokulich do you mind moving the issue there and we can close this one out?

**Comment by nbokulich** [comment]
Yes, moved [here](https://github.com/biocore/emperor/issues/544) — sorry for the misclassification!

**Comment by jairideout** [comment]
Great thanks @nbokulich!

**Comment by ElDeveloper** [comment]
Oh no worries at all, it's great that we are getting user feedback!!!
Thanks again!
