### ISSUE TITLE
q2-emperor broken with Emperor 1.0.0beta7 upgrade

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-emperor#41]
The q2-emperor unit tests passed for the Emperor 1.0.0beta7 upgrade but the [nightly integration tests failed](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/46) when running through the Moving Pictures tutorial. It looks like there's some issue in Emperor with `tojson`:

```shell
Command 'qiime emperor plot --i-pcoa core-metrics-results/unweighted_unifrac_pcoa_results.qza --m-metadata-file sample-metadata.tsv --p-custom-axis DaysSinceExperimentStart --o-visualization core-metrics-results/unweighted-unifrac-emperor.qzv' exited with non-zero return code 1.

stdout:



stderr:


Plugin error from emperor:

  no filter named 'tojson'
```

@ElDeveloper can you look into this today? Ideally we would like to fix this ASAP for tomorrow's release, but if there isn't time we'll revert back to Emperor 1.0.0beta5.

**Comment by ElDeveloper** [comment]
The only situation where I've seen this happening, is when an old version of JINJA2 is installed, however from the looks of the integration tests, version 2.9.6 is installed and this version **does** have the `tojson` filter. In the following example, I create a small template that converts a Python object to a JSON representation using version 2.9.6.

```python
>>> import jinja2
>>> jinja2.__version__
'2.9.6'
>>> env = jinja2.Environment()
>>> temp = env.from_string('{{ obj | tojson }}')
>>> temp.render(obj={'key': 'value', 'key2': [1, 2, None]})
'{"key": "value", "key2": [1, 2, null]}'
```

---------------

I tried reproducing the error by:

1) Installing the q2 stack:

```
conda create -n qiime2-dev --file https://raw.githubusercontent.com/qiime2/environment-files/master/2017.5/staging/qiime2-2017.5-conda-osx-64.txt
```

2) Uninstalling q2-emperor and emperor:

```
pip uninstall q2-emperor emperor
```

3) Installing the latest version of q2-emperor from the git repository:

```
# from the git repo
pip install .
```

4) Installing the latest version of emperor:

```
(q2-disaster) yoshikivazquezbaeza:git_sw$ conda install emperor -c conda-forge
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/yoshikivazquezbaeza/miniconda/envs/q2-disaster:

The following packages will be UPDATED:

    emperor: 1.0.0beta5-py35_2 conda-forge --> 1.0.0beta7-py35_2 conda-forge

Proceed ([y]/n)? y

emperor-1.0.0b 100% |################################| Time: 0:00:00 852.49 kB/s
```

However, after this was done, I was able to execute the command without a problem:

```
(q2-disaster) yoshikivazquezbaeza:moving-pics$ qiime emperor plot --i-pcoa unweighted_unifrac_pcoa_results.qza --m-metadata-file sample-metadata.tsv --o-visualization unifrac
Saved Visualization to: unifrac.qzv
```

**Comment by ElDeveloper** [comment]
I suspect that somewhere, at some point there's an old version of jinja2 being installed, from looking at the JINJA2 release changes [the filter should be available starting version 2.9](https://github.com/pallets/jinja/blob/master/CHANGES#L118). I'm confused as the logs indicate that version 2.9.6 is installed, so this shouldn't be happening.

Is there any way to have access to this service to see I can take a stab at debugging?

**Comment by jairideout** [comment]
I figured out what’s going on: the QIIME 2 docs specify `jinja2==2.8` in a requirements file, which is overriding the jinja2 2.9.6 that’s installed earlier in the conda env. I can’t remember why we pinned jinja 2.8 in the docs — I’m going to remove it and see how the tests go. Thanks for your help with debugging this!

**Comment by jairideout** [comment]
Fixed in https://github.com/qiime2/docs/pull/146
