### ISSUE TITLE
Feature Request: display continuous/categorical in drop-down menu.

### ISSUE THREAD

**Issue by amashchak** [qiime2/q2-emperor#44]
In the drop-down menu, indicate which variables are continuous and which are categorical. 

For categorical variables display the rank  / number of categories.

**Comment by jairideout** [comment]
@amashchak can you post this feature request on the [Emperor issue tracker](https://github.com/biocore/emperor/issues)? This plugin (q2-emperor) wraps the Emperor tool so we try to direct feature requests to the Emperor developers. Once the feature is implemented in Emperor it'll become available in QIIME 2 generated plots. Thanks!
