### ISSUE TITLE
Metadata ID validation

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-emperor#50]
When supplying metadata for a custom axis, it would be pretty awesome to perform some Sample ID validation in the plugin prior to handing off to `emperor`, ensuring that the pcoa results are a subset of the metadata IDs. When `emperor` gets disjoint metadata IDs it doesn't report back *what* IDs are missing, so this makes it a bit difficult for a user to pinpoint. In particular, [this forum post](https://forum.qiime2.org/t/error-in-command-for-generating-pcoa-plot/1251) comes to mind. This would also make this viz consistent with many other QIIME 2 Actions that ensure appropriate ID overlap.

**Comment by ElDeveloper** [comment]
👍  This would also be likely beneficial to have in Emperor.

**Comment by ElDeveloper** [comment]
This issue should be fixed once biocore/emperor#636 is merged.
